language: python
python:
 - "2.7"

install: python setup.py -q install
script: python setup.py test

before_install:
 - wget https://download.elasticsearch.org/elasticsearch/elasticsearch/elasticsearch-0.90.0.deb
 - sudo dpkg -i elasticsearch-0.90.0.deb
 - plugin -install elasticsearch/elasticsearch-transport-thrift/1.5.0
 - pip install .[thrift]

notifications:
  email:
    recipients:
      - dr@nwebs.de
